### ISSUE TITLE
Encode method returns Uint8Array(8) instead of String

### ISSUE THREAD

**Issue by medkhalilbk** [egoroof/blowfish#23]
Hello , im using Nextjs 14 framework and i tried to create hashPassword function using blowfish library 

this is my snippet of code 

```
import { Blowfish } from 'egoroof-blowfish';

 const hashPassword = async (password: string) => {
    try {
        const bf = new Blowfish('super key'); 
        bf.setIv('abcdefgh'); 
        const encoded = bf.encode("122");
        return encoded;
    } catch (error) {
        console.log(error);
    }
 } 
export default hashPassword;
```

and the ouput is Uint8Array(8) [
  54, 169, 29, 134,
  25, 178, 74, 120
]

**Comment by egoroof** [comment]
> Encode method returns Uint8Array(8) instead of String

why you decide it should return string?

**Comment by medkhalilbk** [comment]
Hello @egoroof and thank you for your quick response

I had hoped to obtain a string that could be stored directly in the database

Could you please advise on the best way to handle this Uint8Array output,  should I convert it to a string or does the blowfish library provide a preferred method for this?

**Comment by egoroof** [comment]
you can try something like this:

```js
const strAscii = String.fromCodePoint(...encoded);
const strBase64 = btoa(strAscii);
```

**Comment by egoroof** [comment]
p.s. don't use Blowfish to hash passwords..

**Comment by medkhalilbk** [comment]
Works well, thanks!
