### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by countbytedown** [egoroof/blowfish#3]
I was wondering if this library is compatible with Open SSL implementations?

**Comment by egoroof** [comment]
What do you mean?
It's [tested](https://github.com/egoroof/blowfish/blob/master/test/node.js) against [Node.js crypto module](https://nodejs.org/dist/latest-v7.x/docs/api/crypto.html) which is a wrapper for OpenSSL. So I think the answer is yes (but would be better if you clarify your question).
