### ISSUE TITLE
Decoded data should be multiple of 8 bytes

### ISSUE THREAD

**Issue by jinincarnate** [egoroof/blowfish#5]
Hi Please help,

```
const Blowfish = require('egoroof-blowfish');
const blowFish = new Blowfish('key', Blowfish.MODE.ECB, Blowfish.PADDING.NULL);
const encoded = blowFish.encode('somepassword', Blowfish.TYPE.STRING);
console.log(encoded);
const decoded = blowFish.decode(encoded,Blowfish.TYPE.STRING);
console.log(decoded);
```

Gives ''Error: Decoded data should be multiple of 8 bytes" while trying to decode
Only happens if while encoding Blowfish.TYPE.STRING is used. Works fine if UINT8_ARRAY is used while encoding

**Comment by egoroof** [comment]
That's because encoded bytes cannot be represented correctly in string. Encode should always return raw bytes.
