### ISSUE TITLE
Empty string is not properly decoded

### ISSUE THREAD

**Issue by neilyoung** [egoroof/blowfish#6]
I'm encoding an empty string with a Java app to a padded 8 byte string. The result in JS is an 8 byte UINT8_ARRAY containing just "8", eight times.

`
        var sa = new Blowfish('mycypher', Blowfish.MODE.ECB, Blowfish.PADDING.PKCS5).decode(bytes, Blowfish.TYPE.UINT8_ARRAY)
`

I would expect to receive an empty buffer.

**Comment by egoroof** [comment]
Thanks for reporting!
Fixed in 2.1.0

**Comment by neilyoung** [comment]
Confirmed. Thanks for fixing it.
