### ISSUE TITLE
[BUG] Invalid decode. Returning non 8-bit modular result

### ISSUE THREAD

**Issue by didix16** [egoroof/blowfish#7]
Hi, I'm using this fabulous library for my project. At some point, with a specific data, the decoded data are not the same byte length as the input data.

Example:
```js
let KEY = Buffer.from([0x07, 0x07, 0xBC, 0xDB, 0x0F, 0x0B, 0xAC, 0x29]);
let data = Buffer.from([0xaf, 0x23, 0x99, 0x04, 0x2a, 0x63, 0xf5, 0x4c]);
let bf = new Blowfish(KEY, Blowfish.MODE.ECB);
bf.decode(data,Blowfish.TYPE.UINT8_ARRAY);
// Result: 7-byte length --> <Buffer 00 00 a1 03 00 00 00>
// Expected 8-byte length --><Buffer 00 00 a1 03 00 00 00 00>
```

Awaiting feedback :)

**Comment by egoroof** [comment]
The actual decode result is
```
<Buffer 00 00 a1 03 00 00 00 01>
```
then it unpads to
```
<Buffer 00 00 a1 03 00 00 00>
```
according to [PKCS5 padding](https://github.com/egoroof/blowfish#padding) as it's default padding for this library (until you specify the other one).

This is expected and not a bug.

**Comment by didix16** [comment]
I see, so on decrypt, it strip off the padding bytes , in this case that 0x01 will be stripped off. This means that all decrypted data that ends with 0x01, 0x02 0x02, 0x03, 0x03,0x03 and so until ... 0x08 will be stripped out right?

Thanks for the info @egoroof I 've learned how really works :1st_place_medal:
